### ISSUE TITLE
Throw exceptions in parser

### ISSUE THREAD

**Issue by xyyyzzz** [AY2021S1-CS2113T-F14-2/tp#253]
For instance, throw exceptions if index input / month input by user is invalid, or if user input an empty command.

**Comment by pinfang** [comment]
if the month inputted is incorrect, summary and draw will still execute, need to fix

**Comment by k-walter** [comment]
This was traditionally parsed in Command. If you want to parse in Parser, I can return an Integer but will require some refactoring.

**Comment by k-walter** [comment]
Fixed in #299
