### ISSUE TITLE
Parses invalid clear command

### ISSUE THREAD

**Issue by xyyyzzz** [AY2021S1-CS2113T-F14-2/tp#263]
![image](https://user-images.githubusercontent.com/45732128/98191456-2dbce480-1f54-11eb-8913-a9cec1c3af36.png)

**Comment by xyyyzzz** [comment]
![image](https://user-images.githubusercontent.com/45732128/98364859-7b2c7500-206c-11eb-9a11-ae6ab7fbe253.png)

**Comment by k-walter** [comment]
`clear -s1` is expected cli behaviour. Will update UG on standard cli practices.
